import { Inter, Sora } from "next/font/google";
import "./globals.css";
import HeroBackground from "@/components/HeroBackground";
import CursorEffect from "@/components/CursorEffect";
import Navbar from "@/components/Navbar";

const sora = Sora({
  variable: "--font-sora",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
  display: "swap",
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: {
    default: "AI Video Generator: Story to Animated Video",
    template: "%s | AI Video Generator",
  },
  description:
    "Transform a simple story prompt into a complete animated experience with characters, voices, scenes, and motion, generated by AI.",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${sora.variable} ${inter.variable} antialiased`}>
        <HeroBackground />
        <CursorEffect />
        <Navbar />
        <main>{children}</main>
      </body>
    </html>
  );
}
