"use client";

import { useRef } from "react";
import Image from "next/image";
import Link from "next/link";
import { motion, useScroll, useTransform } from "motion/react";
import { ArrowRight } from "lucide-react";
import AnimatedHeadline from "./AnimatedHeadline";
import ScrollIndicator from "./ScrollIndicator";
import BlurText from "./reactbits/BlurText";
import Magnet from "./reactbits/Magnet";
import ImageParticles from "./ImageParticles";
import storyWorldImage from "../ImageOfProject-centered.png";

export default function Hero() {
  const ref = useRef(null);
  const { scrollYProgress } = useScroll({ target: ref, offset: ["start start", "end start"] });
  const opacity = useTransform(scrollYProgress, [0, 0.7], [1, 0]);
  const y = useTransform(scrollYProgress, [0, 1], [0, 140]);
  const blur = useTransform(scrollYProgress, [0, 0.7], ["blur(0px)", "blur(10px)"]);
  const worldY = useTransform(scrollYProgress, [0, 1], [0, -120]);
  const worldScale = useTransform(scrollYProgress, [0, 1], [1, 1.12]);

  return (
    <section
      id="hero"
      ref={ref}
      className="relative flex min-h-screen flex-col overflow-hidden px-8 pb-8 pt-32 sm:px-14 sm:pb-10 lg:px-24"
    >
      <div className="flex flex-1 flex-col justify-center">
        <div className="mx-auto grid w-full max-w-[1440px] items-center gap-10 lg:grid-cols-12">
          <motion.div style={{ opacity, y, filter: blur }} className="order-2 lg:order-1 lg:col-span-6">
            <AnimatedHeadline baseDelay={0.35} />

            <BlurText
              text="Transform a simple story prompt into a complete animated experience with characters, voices, scenes, and motion, generated by AI."
              delay={28}
              startDelay={1.35}
              stepDuration={0.3}
              direction="bottom"
              className="mt-5 max-w-xl text-base leading-relaxed text-muted sm:text-lg"
            />

            <motion.div
              initial={{ opacity: 0, y: 12 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 1.75, duration: 0.8 }}
              className="mt-7 flex flex-wrap items-center gap-5"
            >
              <Magnet padding={60} magnetStrength={5}>
                <Link
                  href="/create"
                  data-cursor="Create"
                  className="group relative flex items-center gap-3 overflow-hidden rounded-full bg-foreground py-4 pl-7 pr-6 text-sm font-medium text-white shadow-[0_12px_32px_-10px_rgba(37,99,235,0.6)] transition-transform duration-300 hover:scale-[1.03]"
                >
                  <span className="absolute inset-0 bg-gradient-to-r from-deep via-electric to-cyan opacity-0 transition-opacity duration-500 group-hover:opacity-100" />
                  <span className="relative">Create Your Story</span>
                  <ArrowRight size={16} className="relative transition-transform duration-300 group-hover:translate-x-1" />
                </Link>
              </Magnet>
              <Link href="/how-it-works" className="text-sm font-medium text-muted underline-offset-4 transition-colors hover:text-foreground hover:underline">
                See how it works
              </Link>
            </motion.div>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, scale: 0.92 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ delay: 0.3, duration: 1.4, ease: [0.16, 1, 0.3, 1] }}
            style={{ y: worldY, scale: worldScale }}
            className="order-1 mx-auto w-full max-w-[480px] sm:max-w-[640px] lg:order-2 lg:col-span-6 lg:max-w-none"
          >
            <div className="relative">
              <ImageParticles className="pointer-events-none absolute -inset-20 h-[calc(100%+10rem)] w-[calc(100%+10rem)] sm:-inset-28 sm:h-[calc(100%+14rem)] sm:w-[calc(100%+14rem)]" />
              <motion.div
                animate={{ y: [0, -18, 0] }}
                transition={{ duration: 5, repeat: Infinity, ease: "easeInOut" }}
                className="relative"
              >
                <Image
                  src={storyWorldImage}
                  alt="A miniature animated story world floating above a waterfall"
                  priority
                  className="h-auto w-full select-none"
                />
              </motion.div>
            </div>
          </motion.div>
        </div>
      </div>

      <div className="mt-8 flex justify-center">
        <ScrollIndicator delay={2.1} />
      </div>
    </section>
  );
}
